### ISSUE TITLE
Some chars in code blocks are being removed

### ISSUE THREAD

**Issue by tbrowder** [pod-to-pdf/Pod-To-PDF-Lite-raku#3]
For example, given this:

    =begin code
    . bin
    |
    +--
    =end code

The results will be:

    =begin code
      bin
     
    
    =end code

**Comment by dwarring** [comment]
Hi Tom,
If I understand correctly. Spaces are sometimes being removed. I do notice for example if I cut and paste code from the
output PDF some of the spaces have been removed.

I think it's an issue with Raku POD parsing. For example the following, which has some lines with spaces only has the spaces removed on those lines:
```
dd $=pod;
=begin code
  bin

   
=end code

=begin code
  xxxx  
      
  yyyy
  
=end code
```
Produces:
```
[Pod::Block::Code.new(config => {}, contents => ["  bin", "\n", "\n", "\n"]), Pod::Block::Code.new(config => {}, contents => ["  xxxx", "\n", "\n", "  yyyy", "\n", "\n"])]
david@box:~/git/Pod-To-PDF-Lite-raku$ raku /tmp/tst.pod 
[Pod::Block::Code.new(config => {}, contents => ["  bin", "\n", "\n", "\n"]), Pod::Block::Code.new(config => {}, contents => ["  xxxx  ", "\n", "\n", "  yyyy", "\n", "\n"])]
```

**Comment by tbrowder** [comment]
On Wed, Nov 23, 2022 at 19:09 David Warring ***@***.***>
wrote:

> Hi Tom,
> If I understand correctly. Spaces are sometimes being removed. I do notice
> for
>
Interesting, David. I'll check it out more closely.

BTW, the line centering works great! Thanks so much!

-Tom

**Comment by tbrowder** [comment]
David, I ran "raku --doc=Text bad.pod on this pod and it renders correctly:

    =begin pod
    =begin code
    . bin
    |
    +-- foo
    |
    +-- bar
    =end code
    =end pod

I'll keep trying to find where the pipeline bereaks...

**Comment by tbrowder** [comment]
David, the problem is not there any more--probably my error somewhere--but this issue is closed.
